version: "3"

services:
  # CEREBRO DE PYTHON (NUESTRA API Y CHROMIUM)
  bot:
    build: .
    restart: always
    privileged: true
    ports:
      - "5000:5000"
    environment:
      # Ya no usamos Android
      - USE_ANDROID=false
    volumes:
      # Este volumen mantendrá VIVA la sesión de Chrome de LinkedIn, incluso si el bot se reinicia
      - chrome_data:/app/chrome_profile
    command: python app.py

volumes:
  chrome_data:
